# Generated by Django 5.1.6 on 2025-06-15 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brief_exp', models.CharField(blank=True, max_length=100, null=True)),
                ('subject', models.CharField(blank=True, choices=[('turkce', 'Türkçe'), ('temel_matematik', 'Temel Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('biyoloji', 'Biyoloji'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('din', 'Din Kültürü ve Ahlak Bilgisi'), ('matematik', 'Matematik'), ('edebiyat', 'Türk Dili ve Edebiyatı'), ('tarih1', 'Tarih-1'), ('tarih2', 'Tarih-2'), ('cografya1', 'Coğrafya-1'), ('cografya2', 'Coğrafya-2'), ('psikoloji', 'Psikoloji'), ('sosyoloji', 'Sosyoloji'), ('mantik', 'Mantık'), ('ingilizce', 'İngilizce'), ('almanca', 'Almanca'), ('fransizca', 'Fransızca')], max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=1000, null=True)),
                ('subject', models.CharField(blank=True, choices=[('turkce', 'Türkçe'), ('temel_matematik', 'Temel Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('biyoloji', 'Biyoloji'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('din', 'Din Kültürü ve Ahlak Bilgisi'), ('matematik', 'Matematik'), ('edebiyat', 'Türk Dili ve Edebiyatı'), ('tarih1', 'Tarih-1'), ('tarih2', 'Tarih-2'), ('cografya1', 'Coğrafya-1'), ('cografya2', 'Coğrafya-2'), ('psikoloji', 'Psikoloji'), ('sosyoloji', 'Sosyoloji'), ('mantik', 'Mantık'), ('ingilizce', 'İngilizce'), ('almanca', 'Almanca'), ('fransizca', 'Fransızca')], max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('option_a', models.CharField(blank=True, max_length=100, null=True)),
                ('option_b', models.CharField(blank=True, max_length=100, null=True)),
                ('option_c', models.CharField(blank=True, max_length=100, null=True)),
                ('option_d', models.CharField(blank=True, max_length=100, null=True)),
                ('option_e', models.CharField(blank=True, max_length=100, null=True)),
                ('correct_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, choices=[('EDU', 'educational'), ('HELP', 'help'), ('GENERAL', 'general')], max_length=50, null=True)),
                ('attachments', models.FileField(blank=True, max_length=255, null=True, upload_to='attachments/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='api.postmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(blank=True, choices=[('turkce', 'Türkçe'), ('temel_matematik', 'Temel Matematik'), ('fizik', 'Fizik'), ('kimya', 'Kimya'), ('biyoloji', 'Biyoloji'), ('tarih', 'Tarih'), ('cografya', 'Coğrafya'), ('felsefe', 'Felsefe'), ('din', 'Din Kültürü ve Ahlak Bilgisi'), ('matematik', 'Matematik'), ('edebiyat', 'Türk Dili ve Edebiyatı'), ('tarih1', 'Tarih-1'), ('tarih2', 'Tarih-2'), ('cografya1', 'Coğrafya-1'), ('cografya2', 'Coğrafya-2'), ('psikoloji', 'Psikoloji'), ('sosyoloji', 'Sosyoloji'), ('mantik', 'Mantık'), ('ingilizce', 'İngilizce'), ('almanca', 'Almanca'), ('fransizca', 'Fransızca')], max_length=100, null=True)),
                ('questions', models.ManyToManyField(related_name='tests', to='api.questionsmodel')),
            ],
        ),
    ]
