# Generated by Django 5.1.6 on 2025-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_commentmodel_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='attachments',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='attachments/'),
        ),
    ]
