# Generated by Django 5.2.1 on 2025-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_postmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('EDU', 'educational'), ('HELP', 'help'), ('GENERAL', 'general')], max_length=50, null=True),
        ),
    ]
