# Generated by Django 5.2.1 on 2025-06-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
