# Generated by Django 5.2.1 on 2025-06-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_postmodel_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('question', models.CharField(max_length=1000, null=True)),
                ('subject', models.CharField(choices=[('MATH', 'math'), ('GEOGRAPHY', 'geography'), ('LITERATURE', 'literature')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('option_a', models.CharField(max_length=100, null=True)),
                ('option_b', models.CharField(max_length=100, null=True)),
                ('option_c', models.CharField(max_length=100, null=True)),
                ('option_d', models.CharField(max_length=100, null=True)),
                ('option_e', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
