# Generated by Django 5.2.1 on 2025-06-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_questionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(choices=[('MATH', 'math'), ('GEOGRAPHY', 'geography'), ('LITERATURE', 'literature')], null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
            ],
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(related_name='tests', to='api.questionsmodel')),
            ],
        ),
    ]
