# Generated by Django 5.2.1 on 2025-06-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_notesmodel_questionsmodel_tag_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='subject',
            field=models.CharField(choices=[('MATH', 'math'), ('GEOGRAPHY', 'geography'), ('LITERATURE', 'literature')], null=True),
        ),
    ]
