# Generated by Django 5.2.1 on 2025-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_testmodel_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsmodel',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], null=True),
        ),
    ]
